### ISSUE TITLE
can you please prevent this theme from showing random clutter in my sidebar?

### ISSUE THREAD

**Issue by incantatem1** [Avesend/obsidian-lumines#1]
the theme looks so nice, but all the 7z archives in my sidebar annoy me. they are in my vault for backups.

**Comment by ghost** [comment]
I’m not entirely sure I understand what you mean. Could you please provide more information or a screenshot of the issue?

**Comment by incantatem1** [comment]
![image](https://github.com/user-attachments/assets/e2985eb3-a48f-4111-b348-8c12cdad08fd)

screenshot (sorry for cut off stuff, but privacy)

**Comment by Avesend** [comment]
Thank you for the screenshot. I understand the issue now and will address it as soon as possible.

**Comment by ghost** [comment]
Thanks for the screenshot. I understand the issue now and will address it soon.

**Comment by ghost** [comment]
The tag will be displayed if the file format is an image, such as jpeg, jpg, png, webp, or gif.

The fix will be available in the next version of the theme.

**Comment by incantatem1** [comment]
> The tag will be displayed if the file format is an image, such as jpeg, jpg, png, webp, or gif.
> 
> The fix will be available in the next version of the theme.

does this include the files itself? i want the files gone from the sidebar, not just the file format tags. sorry if this was unclear, i didn't want to screenshot my actual files

**Comment by Avesend** [comment]
The issue has been fixed. I will publish a new version of the theme shortly.

**Comment by ghost** [comment]
The issue has been fixed, and the theme can be updated.

**Comment by incantatem1** [comment]
nice, thanks <3
