### ISSUE TITLE
please bring the standard purple back

### ISSUE THREAD

**Issue by incantatem1** [Avesend/obsidian-lumines#2]
or add an option for either using the standard purple or your own accent color. (i don't want to change my accent color to the standard purple because i use lots of themes in which purple just doesn't look good.)

**Comment by incantatem1** [comment]
or maybe just add the option to choose any accent color fo the theme, unconnected to main accent.

**Comment by ghost** [comment]
The theme was designed with a focus on improving the classic Obsidian interface. That’s why, in previous versions of the theme, certain parts of the code had colors hardcoded based on #8A5CF5 (the color suggested by Obsidian).

As a result, when users wanted to change the accent color in the settings, parts of the interface, like the sidebar, would still remain purple. I thought that not everyone would want to use the default purple color, so in the new version of the theme, I removed the hardcoded color values and replaced them with the variable var(--color-accent).

> i don’t want to change my accent color to the standard purple

The “Lumines” theme has always been based on the default purple. I never created a new accent color. For example, in the previous version of the theme, the first folder in the sidebar had the default purple color (#8A5CF5).

*Please note*: English is not my first language, so I apologize if there are any mistakes in my message.

**Comment by ghost** [comment]
I don’t fully understand your request, but I can set the **previous color** (default purple #8A5CF5) in the var(--accent-color) variable in the theme’s CSS code if that helps with the issue.

**Comment by incantatem1** [comment]
ok, to make that more clear:

my selected accent color is 918983 (a pale brown). this looks good in many themes i use because it's mostly academia aesthetic stuff.

i installed lumines because i liked the standard obsidian purple in it so much, it looked so glowy without being overwhelming. but now it's this pale brown which looks..... dull. 

if i change my pale brown to the purple again, though, i'll have that purple in many of my academia themes which looks honestly shitty and clashy. 

therefore i'd prefer an option to use the standard purple in lumines, or even better, any desired color WITHOUT changing the general accent (the pale brown in my case) to something else.

**Comment by incantatem1** [comment]
i would be happy if you did set it back to the purple like mentioned in your other post, but i think most people would be the most happy if it was changeable within style settings or something.

**Comment by ghost** [comment]
Let me know if I understand correctly: You want to set the accent color to #918983 in the Obsidian settings, but have the main color for folders in the sidebar remain #8A5CF5?

**Comment by ghost** [comment]
If I understand correctly, I can offer an alternative: Since I want the theme to be adaptable for each user, it will remain as is. However, as an exception, I can create a class, for example, .sidebar-purple, so you can have a purple sidebar locally. Are you familiar with using [cssclasses](https://github.com/Avesend/obsidian-lumines/blob/main/assets/readme-cover-3.png)?

**Comment by incantatem1** [comment]
um, wouldn't that require me to add the class to every single document? seems excessive.

i'd rather just uninstall the theme then, sorry T_T

**Comment by ghost** [comment]
The class only needs to be added to one document.

**Comment by incantatem1** [comment]
> Let me know if I understand correctly: You want to set the accent color to #918983 in the Obsidian settings, but have the main color for folders in the sidebar remain #8A5CF5?

yes (sorry if i misunderstand this now too, i feel overwhelmed and don't know what's going on anymore)

**Comment by incantatem1** [comment]
> The class only needs to be added to one document.

if that works, and doesn't simultaneously mess up all my other themes, then ok. i've only used classes that affected the document they're attached to.

**Comment by ghost** [comment]
I tried various methods to implement the solution I proposed, but I wasn’t able to realize it.

However, I can adapt the theme for the “Style Settings” plugin, which will allow you to manually set the color for folders. It’s the same cssclasses property but with a interface.

**Comment by incantatem1** [comment]
> I tried various methods to implement the solution I proposed, but I wasn’t able to realize it.
> 
> However, I can adapt the theme for the “Style Settings” plugin, which will allow you to manually set the color for folders. It’s the same cssclasses property but with a interface.

that's the best, thank you.

**Comment by ghost** [comment]
Update released. The theme now supports the ”Style Settings” plugin. In your case, you need to select the ”Theme” color option for folders.

**Comment by incantatem1** [comment]
the update is very nice and makes me happy <3

**Comment by incantatem1** [comment]
Why are the style settings gone again? T_T

**Comment by ghost** [comment]
> Why are the style settings gone again? T_T

The removal of the Style Settings integration is only temporary. I plan to restore this feature by Friday this week (and I’m trying to make it available sooner). The reason for its removal was due to some inconsistencies that arose when using the manual folder name color customization feature, particularly during the work on improving the light and dark themes. Since I plan to release the updated themes together, I decided to temporarily disable this feature. Thank you for your understanding and patience!

**Comment by ghost** [comment]
The release is delayed until saturday.

**Comment by ghost** [comment]
✅
